### ISSUE TITLE
how to change pins for STM32F103C8T6

### ISSUE THREAD

**Issue by MohammadMokhalled** [stevstrong/Adafruit_TFTLCD_8bit_STM32#3]
My STM32 board doesn't have PB2 pin to use. How can I change the data pins definition??

**Comment by stevstrong** [comment]
Well, it depends on which board do you use.
The blue pill has this pin, but it requires a bit of work, as discussed here: http://stm32duino.com/viewtopic.php?f=44&t=637&hilit=PB2&start=70#p16222
Otherwise you can set the data port here: http://stm32duino.com/viewtopic.php?f=44&t=637&hilit=PB2&start=70#p16222.

**Comment by MohammadMokhalled** [comment]
thank you
I found PB2 on my board...
but it still not works for ili9325 tft lcd...how can i fix it??

**Comment by stevstrong** [comment]
Have you read the forum? Specially this thread: http://stm32duino.com/viewtopic.php?f=9&t=763&hilit=david&start=90#p24715?
Please use the forum for such kind problems, unless you have found a bug which has to be corrected.
